// src/utils/audioMap.js
// Auto-generated by scripts/generate_audio.js — DO NOT edit manually.
// Re-run `node scripts/generate_audio.js` to update.

export const audioMap = {
  "A hawker uncle has one hundred fishballs on each tray.": "/assets/audio/audio_a_hawker_uncle_has_one_hundred_fishballs_on_each_tray_0.mp3",
  "He has three full trays. How many fishballs is that?": "/assets/audio/audio_he_has_three_full_trays_how_many_fishballs_is_that_0.mp3",
  "Hmm... can you figure it out before we open the trays?": "/assets/audio/audio_hmm_can_you_figure_it_out_before_we_open_the_trays_0.mp3",
  "Mei Ling goes to the wet market with her grandmother every Saturday.": "/assets/audio/audio_mei_ling_goes_to_the_wet_market_with_her_grandmother_every_s_0.mp3",
  "Today they are counting eggs for a big order!": "/assets/audio/audio_today_they_are_counting_eggs_for_a_big_order_0.mp3",
  "One full tray has one hundred eggs.": "/assets/audio/audio_one_full_tray_has_one_hundred_eggs_0.mp3",
  "That is ONE HUNDRED. We write it as 100.": "/assets/audio/audio_that_is_one_hundred_we_write_it_as_100_0.mp3",
  "It has the digit 1 in the hundreds place, and zeros in the tens and ones places.": "/assets/audio/audio_it_has_the_digit_1_in_the_hundreds_place_and_zeros_in_the_te_0.mp3",
  "Two trays have two hundred eggs. Three trays have three hundred eggs.": "/assets/audio/audio_two_trays_have_two_hundred_eggs_three_trays_have_three_hundr_0.mp3",
  "We are counting in hundreds: one hundred, two hundred, three hundred, all the way to one thousand!": "/assets/audio/audio_we_are_counting_in_hundreds_one_hundred_two_hundred_three_hu_0.mp3",
  "Mei Ling finds two full trays, three rows of ten, and five single eggs.": "/assets/audio/audio_mei_ling_finds_two_full_trays_three_rows_of_ten_and_five_sin_0.mp3",
  "That gives us two hundred and thirty-five eggs altogether!": "/assets/audio/audio_that_gives_us_two_hundred_and_thirtyfive_eggs_altogether_0.mp3",
  "Two hundred and thirty-five is written as 235.": "/assets/audio/audio_two_hundred_and_thirtyfive_is_written_as_235_0.mp3",
  "In expanded form: 200 plus 30 plus 5 equals 235.": "/assets/audio/audio_in_expanded_form_200_plus_30_plus_5_equals_235_0.mp3",
  "Now YOU can build any number up to one thousand!": "/assets/audio/audio_now_you_can_build_any_number_up_to_one_thousand_0.mp3",
  "Let's build numbers using hundreds, tens, and ones blocks!": "/assets/audio/audio_lets_build_numbers_using_hundreds_tens_and_ones_blocks_0.mp3",
  "Drag the blue hundred flats, orange ten rods, and green unit cubes to make the target number.": "/assets/audio/audio_drag_the_blue_hundred_flats_orange_ten_rods_and_green_unit_c_0.mp3",
  "Now let's fill in the place value chart.": "/assets/audio/audio_now_lets_fill_in_the_place_value_chart_0.mp3",
  "How many hundreds, tens, and ones does this number have?": "/assets/audio/audio_how_many_hundreds_tens_and_ones_does_this_number_have_0.mp3",
  "Great work! Now let's place numbers on the number line and compare them.": "/assets/audio/audio_great_work_now_lets_place_numbers_on_the_number_line_and_com_0.mp3",
  "Which number is greater? Look at the hundreds digit first!": "/assets/audio/audio_which_number_is_greater_look_at_the_hundreds_digit_first_0.mp3",
  "Brilliant! You know your hundreds!": "/assets/audio/audio_brilliant_you_know_your_hundreds_0.mp3",
  "Let's look at the place value chart again!": "/assets/audio/audio_lets_look_at_the_place_value_chart_again_0.mp3",
  "What does the hundreds digit in a number tell us?": "/assets/audio/audio_what_does_the_hundreds_digit_in_a_number_tell_us_0.mp3",
  "Think about the egg trays from the story. Can you explain it?": "/assets/audio/audio_think_about_the_egg_trays_from_the_story_can_you_explain_it_0.mp3",
};
